### ISSUE TITLE
你好，怎么直接分离视频的手势并存为适用于EchoMimicV2的npy文件

### ISSUE THREAD

**Issue by LSliu666** [smthemex/ComfyUI_Sapiens#10]
你好，怎么直接分离视频的手势并存为适用于EchoMimicV2的npy文件

**Comment by LSliu666** [comment]
选择save_pose即可默认保存

**Comment by LSliu666** [comment]
emmm,输出的npy文件不可以直接用于EchoMimicV2原始项目，该怎么转

**Comment by g711ab** [comment]
同样问题，报错：!!! Exception during processing !!! list indices must be integers or slices, not str

**Comment by LSliu666** [comment]
可能作者的Comfyui版EchoMimic可以用，但是原项目的报错

**Comment by smthemex** [comment]
EchoMimic的新版已集成sapiens的pose，不需要再用这个来生成npy文件

**Comment by Falkonar** [comment]
不需要再用这个来生成npy文件 ? 对不起，但我不明白我现在如何创建npy文件。 我没有看到任何其他方法。
