### ISSUE TITLE
TorchScript BF16 Model

### ISSUE THREAD

**Issue by lyxkilo** [smthemex/ComfyUI_Sapiens#2]
Thanks for creating this repo!

To save some disk space, if the bf16 models from the official repo cannot be used, is it possible to convert the torchscript models to bf16 or other precision and use them?

**Comment by smthemex** [comment]
At present, the official FP16 model cannot run due to the chaotic built-in version of the official model and the loading method provided by the official. For example, the built-in version number requirement is int, but the result on huggingface is float
目前官方的fp16模型，因为官方模型内置版本混乱，官方提供的加载方式无法运行。比如内置的版本号需求是int，结果huggingface上的是float

**Comment by lyxkilo** [comment]
Well, hope that they can get it fixed soon...

I manually did a basic conversion for the official torchscript model to bf16 and it seems okay to run. I'm not sure if it's the correct way though.

Conversion code 
```
model.eval().to("cuda").to(torch.bfloat16)
```

Modification to the repo after converting the models

1. In sapiens_node.py, add "bf16_torch" in "dtype" choices in SapiensLoader node.
2. In Sapiens_Pytorch/common.py, for process_image() in all the processor classes, add a model_dtype paramter e.g.
```
    def process_image(self, image: Image.Image, model,select_obj,RGB_BG, model_dtype: torch.dtype = torch.float32):
        input_tensor = self.transform_fn(image).unsqueeze(0).to("cuda").to(model_dtype)
```
3. For all code calling process_image() above, add a model_dtype argument

I'm sorry that I'm not familiar with the ComfyUI nodes. Could you please check if it's okay to implement? Thank you.

**Comment by smthemex** [comment]
f it only runs on FP16, it seems to work according to your code, and I will test it

**Comment by lyxkilo** [comment]
> f it only runs on FP16, it seems to work according to your code, and I will test it

Thank you! I just made a small modification here https://github.com/smthemex/ComfyUI_Sapiens/pull/3, just for your reference.

**Comment by smthemex** [comment]
nice work.
