### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by T8mars** [smthemex/ComfyUI_Sapiens#4]
这个是否可以优化下，经常发生GPU 100%卡的页面都变卡的情况，只有重启COMFYUI才行

**Comment by T8mars** [comment]
![image](https://github.com/user-attachments/assets/f293e68e-ec6a-4a48-bd18-f999605c8cd9)
这边跑完后他也没有卸载模型，哪怕我加了LAYERSTYLE的卸载模型也没用

**Comment by smthemex** [comment]
你是用32还是16的，上次有网友PR了16版本的，我还没有测试16的实际效果。模型卸载这里，因为没有加入comfyUI的模型管理，所以我还要单写几行卸载代码。

**Comment by smthemex** [comment]
新版本已加入模型卸载代码

**Comment by T8star1984** [comment]
好的谢谢，我都用过了，多运行几次就卡的不行之前

**Comment by T8star1984** [comment]
感谢，更新！
